"""
All podcast settings.
"""
from django.conf import settings

# Django by default verifies a URL whening using URLField. Make this optional
VERIFY_URLS = getattr(settings, 'PODCAST_VERIFY_URLS', True)

PARENT_CHOICES = (
    ('Arts', 'Arts'),
    ('Business', 'Business'),
    ('Comedy', 'Comedy'),
    ('Education', 'Education'),
    ('Games & Hobbies', 'Games & Hobbies'),
    ('Government & Organizations', 'Government & Organizations'),
    ('Health', 'Health'),
    ('Kids & Family', 'Kids & Family'),
    ('Music', 'Music'),
    ('News & Politics', 'News & Politics'),
    ('Religion & Spirituality', 'Religion & Spirituality'),
    ('Science & Medicine', 'Science & Medicine'),
    ('Society & Culture', 'Society & Culture'),
    ('Sports & Recreation', 'Sports & Recreation'),
    ('Technology', 'Technology'),
    ('TV & Film', 'TV & Film'),
)
CHILD_CHOICES = (
    ('Arts', (
            ('Design', 'Design'),
            ('Fashion & Beauty', 'Fashion & Beauty'),
            ('Food', 'Food'),
            ('Literature', 'Literature'),
            ('Performing Arts', 'Performing Arts'),
            ('Visual Arts', 'Visual Arts'),
        )
    ),
    ('Business', (
            ('Business News', 'Business News'),
            ('Careers', 'Careers'),
            ('Investing', 'Investing'),
            ('Management & Marketing', 'Management & Marketing'),
            ('Shopping', 'Shopping'),
        )
    ),
    ('Education', (
            ('Education Technology', 'Education Technology'),
            ('Higher Education', 'Higher Education'),
            ('K-12', 'K-12'),
            ('Language Courses', 'Language Courses'),
            ('Training', 'Training'),
        )
    ),
    ('Games & Hobbies', (
            ('Automotive', 'Automotive'),
            ('Aviation', 'Aviation'),
            ('Hobbies', 'Hobbies'),
            ('Other Games', 'Other Games'),
            ('Video Games', 'Video Games'),
        )
    ),
    ('Government & Organizations', (
            ('Local', 'Local'),
            ('National', 'National'),
            ('Non-Profit', 'Non-Profit'),
            ('Regional', 'Regional'),
        )
    ),
    ('Health', (
            ('Alternative Health', 'Alternative Health'),
            ('Fitness & Nutrition', 'Fitness & Nutrition'),
            ('Self-Help', 'Self-Help'),
            ('Sexuality', 'Sexuality'),
        )
    ),
    ('Religion & Spirituality', (
            ('Buddhism', 'Buddhism'),
            ('Christianity', 'Christianity'),
            ('Hinduism', 'Hinduism'),
            ('Islam', 'Islam'),
            ('Judaism', 'Judaism'),
            ('Other', 'Other'),
            ('Spirituality', 'Spirituality'),
        )
    ),
    ('Science & Medicine', (
            ('Medicine', 'Medicine'),
            ('Natural Sciences', 'Natural Sciences'),
            ('Social Sciences', 'Social Sciences'),
        )
    ),
    ('Society & Culture', (
            ('History', 'History'),
            ('Personal Journals', 'Personal Journals'),
            ('Philosophy', 'Philosophy'),
            ('Places & Travel', 'Places & Travel'),
        )
    ),
    ('Sports & Recreation', (
            ('Amateur', 'Amateur'),
            ('College & High School', 'College & High School'),
            ('Outdoor', 'Outdoor'),
            ('Professional', 'Professional'),
        )
    ),
    ('Technology', (
            ('Gadgets', 'Gadgets'),
            ('Tech News', 'Tech News'),
            ('Podcasting', 'Podcasting'),
            ('Software How-To', 'Software How-To'),
        )
    ),
)

COPYRIGHT_CHOICES = (
    ('All rights reserved', 'All rights reserved'),
    ('Creative Commons: Attribution (by)', 'Creative Commons: Attribution (by)'),
    ('Creative Commons: Attribution-Share Alike (by-sa)', 'Creative Commons: Attribution-Share Alike (by-sa)'),
    ('Creative Commons: Attribution-No Derivatives (by-nd)', 'Creative Commons: Attribution-No Derivatives (by-nd)'),
    ('Creative Commons: Attribution-Non-Commercial (by-nc)', 'Creative Commons: Attribution-Non-Commercial (by-nc)'),
    ('Creative Commons: Attribution-Non-Commercial-Share Alike (by-nc-sa)', 'Creative Commons: Attribution-Non-Commercial-Share Alike (by-nc-sa)'),
    ('Creative Commons: Attribution-Non-Commercial-No Dreivatives (by-nc-nd)', 'Creative Commons: Attribution-Non-Commercial-No Dreivatives (by-nc-nd)'),
    ('Public domain', 'Public domain'),
)
EXPLICIT_CHOICES = (
    ('Yes', 'Yes'),
    ('No', 'No'),
    ('Clean', 'Clean'),
)
MEDIA_CATEGORY_CHOICES = (
    ('Action & Adventure', 'Action & Adventure'),
    ('Ads & Promotional', 'Ads & Promotional'),
    ('Anime & Animation', 'Anime & Animation'),
    ('Art & Experimental', 'Art & Experimental'),
    ('Business', 'Business'),
    ('Children & Family', 'Children & Family'),
    ('Comedy', 'Comedy'),
    ('Dance', 'Dance'),
    ('Documentary', 'Documentary'),
    ('Drama', 'Drama'),
    ('Educational', 'Educational'),
    ('Faith & Spirituality', 'Faith & Spirituality'),
    ('Health & Fitness', 'Health & Fitness'),
    ('Foreign', 'Foreign'),
    ('Gaming', 'Gaming'),
    ('Gay & Lesbian', 'Gay & Lesbian'),
    ('Home Video', 'Home Video'),
    ('Horror', 'Horror'),
    ('Independent', 'Independent'),
    ('Mature & Adult', 'Mature & Adult'),
    ('Movie (feature)', 'Movie (feature)'),
    ('Movie (short)', 'Movie (short)'),
    ('Movie Trailer', 'Movie Trailer'),
    ('Music & Musical', 'Music & Musical'),
    ('Nature', 'Nature'),
    ('News', 'News'),
    ('Political', 'Political'),
    ('Religious', 'Religious'),
    ('Romance', 'Romance'),
    ('Independent', 'Independent'),
    ('Sci-Fi & Fantasy', 'Sci-Fi & Fantasy'),
    ('Science & Technology', 'Science & Technology'),
    ('Special Interest', 'Special Interest'),
    ('Sports', 'Sports'),
    ('Stock Footage', 'Stock Footage'),
    ('Thriller', 'Thriller'),
    ('Travel', 'Travel'),
    ('TV Show', 'TV Show'),
    ('Western', 'Western'),
)
STATUS_CHOICES = (
    (1, 'Draft'),
    (2, 'Public'),
    (3, 'Private'),
)
SECONDS_CHOICES = tuple(('%02d' % x, str(x)) for x in range(60))
TYPE_CHOICES = (
    ('Plain', 'Plain text'),
    ('HTML', 'HTML'),
)
ROLE_CHOICES = (
    ('Actor', 'Actor'),
    ('Adaptor', 'Adaptor'),
    ('Anchor person', 'Anchor person'),
    ('Animal Trainer', 'Animal Trainer'),
    ('Animator', 'Animator'),
    ('Announcer', 'Announcer'),
    ('Armourer', 'Armourer'),
    ('Art Director', 'Art Director'),
    ('Artist/Performer', 'Artist/Performer'),
    ('Assistant Camera', 'Assistant Camera'),
    ('Assistant Chief Lighting Technician', 'Assistant Chief Lighting Technician'),
    ('Assistant Director', 'Assistant Director'),
    ('Assistant Producer', 'Assistant Producer'),
    ('Assistant Visual Editor', 'Assistant Visual Editor'),
    ('Author', 'Author'),
    ('Broadcast Assistant', 'Broadcast Assistant'),
    ('Broadcast Journalist', 'Broadcast Journalist'),
    ('Camera Operator', 'Camera Operator'),
    ('Carpenter', 'Carpenter'),
    ('Casting', 'Casting'),
    ('Causeur', 'Causeur'),
    ('Chief Lighting Technician', 'Chief Lighting Technician'),
    ('Choir', 'Choir'),
    ('Choreographer', 'Choreographer'),
    ('Clapper Loader', 'Clapper Loader'),
    ('Commentary or Commentator', 'Commentary or Commentator'),
    ('Commissioning Broadcaster', 'Commissioning Broadcaster'),
    ('Composer', 'Composer'),
    ('Computer programmer', 'Computer programmer'),
    ('Conductor', 'Conductor'),
    ('Consultant', 'Consultant'),
    ('Continuity Checker', 'Continuity Checker'),
    ('Correspondent', 'Correspondent'),
    ('Costume Designer', 'Costume Designer'),
    ('Dancer', 'Dancer'),
    ('Dialogue Coach', 'Dialogue Coach'),
    ('Director', 'Director'),
    ('Director of Photography', 'Director of Photography'),
    ('Distribution Company', 'Distribution Company'),
    ('Draughtsman', 'Draughtsman'),
    ('Dresser', 'Dresser'),
    ('Dubber', 'Dubber'),
    ('Editor/Producer (News)', 'Editor/Producer (News)'),
    ('Editor-in-chief', 'Editor-in-chief'),
    ('Editor-of-the-Day', 'Editor-of-the-Day'),
    ('Ensemble', 'Ensemble'),
    ('Executive Producer', 'Executive Producer'),
    ('Expert', 'Expert'),
    ('Fight Director', 'Floor Manager'),
    ('Floor Manager', 'Floor Manager'),
    ('Focus Puller', 'Focus Puller'),
    ('Foley Artist', 'Foley Artist'),
    ('Foley Editor', 'Foley Editor'),
    ('Foley Mixer', 'Foley Mixer'),
    ('Graphic Assistant', 'Graphic Assistant'),
    ('Graphic Designer', 'Graphic Designer'),
    ('Greensman', 'Greensman'),
    ('Grip', 'Grip'),
    ('Hairdresser', 'Hairdresser'),
    ('Illustrator', 'Illustrator'),
    ('Interviewed Guest', 'Interviewed Guest'),
    ('Interviewer', 'Interviewer'),
    ('Key Character', 'Key Character'),
    ('Key Grip', 'Key Grip'),
    ('Key Talents', 'Key Talents'),
    ('Leadman', 'Leadman'),
    ('Librettist', 'Librettist'),
    ('Lighting director', 'Lighting director'),
    ('Lighting Technician', 'Lighting Technician'),
    ('Location Manager', 'Location Manager'),
    ('Lyricist', 'Lyricist'),
    ('Make Up Artist', 'Make Up Artist'),
    ('Manufacturer', 'Manufacturer'),
    ('Matte Artist', 'Matte Artist'),
    ('Music Arranger', 'Music Arranger'),
    ('Music Group', 'Music Group'),
    ('Musician', 'Musician'),
    ('News Reader', 'News Reader'),
    ('Orchestra', 'Orchestra'),
    ('Participant', 'Participant'),
    ('Photographer', 'Photographer'),
    ('Post-Production Editor', 'Post-Production Editor'),
    ('Producer', 'Producer'),
    ('Production Assistant', 'Production Assistant'),
    ('Production Company', 'Production Company'),
    ('Production Department', 'Production Department'),
    ('Production Manager', 'Production Manager'),
    ('Production Secretary', 'Production Secretary'),
    ('Programme Production Researcher', 'Programme Production Researcher'),
    ('Property Manager', 'Property Manager'),
    ('Publishing Company', 'Publishing Company'),
    ('Puppeteer', 'Puppeteer'),
    ('Pyrotechnician', 'Pyrotechnician'),
    ('Reporter', 'Reporter'),
    ('Rigger', 'Rigger'),
    ('Runner', 'Runner'),
    ('Scenario', 'Scenario'),
    ('Scenic Operative', 'Scenic Operative'),
    ('Script Supervisor', 'Script Supervisor'),
    ('Second Assistant Camera', 'Second Assistant Camera'),
    ('Second Assistant Director', 'Second Assistant Director'),
    ('Second Unit Director', 'Second Unit Director'),
    ('Set Designer', 'Set Designer'),
    ('Set Dresser', 'Set Dresser'),
    ('Sign Language', 'Sign Language'),
    ('Singer', 'Singer'),
    ('Sound Designer', 'Sound Designer'),
    ('Sound Mixer', 'Sound Mixer'),
    ('Sound Recordist', 'Sound Recordist'),
    ('Special Effects', 'Special Effects'),
    ('Stunts', 'Stunts'),
    ('Subtitles', 'Subtitles'),
    ('Technical Director', 'Technical Director'),
    ('Translation', 'Translation'),
    ('Transportation Manager', 'Transportation Manager'),
    ('Treatment / Programme Proposal', 'Treatment / Programme Proposal'),
    ('Vision Mixer', 'Vision Mixer'),
    ('Visual Editor', 'Visual Editor'),
    ('Visual Effects', 'Visual Effects'),
    ('Wardrobe', 'Wardrobe'),
    ('Witness', 'Witness'),
)
STANDARD_CHOICES = (
    ('Simple', 'Simple'),
    ('MPAA', 'MPAA'),
    ('V-chip', 'TV Parental Guidelines'),
)
RATING_CHOICES = (
    ('Simple', (
            ('Adult', 'Adult'),
            ('Nonadult', 'Non-adult'),
        )
    ),
    ('MPAA', (
            ('G', 'G: General Audiences'),
            ('PG', 'PG: Parental Guidance Suggested'),
            ('PG-13', 'PG-13: Parents Strongly Cautioned'),
            ('R', 'R: Restricted'),
            ('NC-17', 'NC-17: No One 17 and Under Admitted'),
        )
    ),
    ('TV Parental Guidelines', (
            ('TV-Y', 'TV-Y: All children'),
            ('TV-Y7-FV', 'TV-Y7/TV-Y7-FV: Directed to older children'),
            ('TV-G', 'TV-G: General audience'),
            ('TV-PG', 'TV-PG: Parental guidance'),
            ('TV-14', 'TV-14: Parents strongly cautioned'),
            ('TV-MA', 'TV-MA: Mature audiences'),
        )
    ),
)
FREQUENCY_CHOICES = (
    ('always', 'Always'),
    ('hourly', 'Hourly'),
    ('daily', 'Daily'),
    ('weekly', 'Weekly'),
    ('monthly', 'Monthly'),
    ('yearly', 'Yearly'),
    ('never', 'Never'),
)
MIME_CHOICES = (
    ('audio/mpeg', '.mp3 (audio)'),
    ('audio/x-m4a', '.m4a (audio)'),
    ('video/mp4', '.mp4 (audio or video)'),
    ('video/x-m4v', '.m4v (video)'),
    ('video/quicktime', '.mov (video)'),
    ('application/pdf', '.pdf (document)'),
    ('image/jpeg', '.jpg, .jpeg, .jpe (image)')
)
MEDIUM_CHOICES = (
    ('Audio', 'Audio'),
    ('Video', 'Video'),
    ('Document', 'Document'),
    ('Image', 'Image'),
    ('Executable', 'Executable'),
)
EXPRESSION_CHOICES = (
    ('Sample', 'Sample'),
    ('Full', 'Full'),
    ('Nonstop', 'Non-stop'),
)
ALGO_CHOICES = (
    ('MD5', 'MD5'),
    ('SHA-1', 'SHA-1'),
)